### ISSUE TITLE
Incorrect response when requesting domain details

### ISSUE THREAD

**Issue by laurisb** [SIWECOS/siwecos-business-layer#158]
I have two test domains: A (domainId: 20131, tokenId: 3759) and B (domainId: 20016, tokenId: 3642). Both are registered domain names and have hosting.

When requesting details for domain A, the correct response is returned.

But for domain B the response always is HTTP 403, which means that SIWECOS-Token is invalid, despite same token used for all API requests.

**Comment by Lednerb** [comment]
@laurisb 

It seems that everything is correct.

The problem is the following: As you've wrote, the token_ids are not the same. For Domain A you have registered the domain to your external token for the plugin (id `3759`)

Domain B was firstly used with a freescan, so it still belongs to the global Freescan-Token and not to your external token for API-usage.

To bind the domain B to your correct token you have to verify the domain first.
Afterwards you should be able to retrieve the domain details.
